# Data Analysis
- Numpy
- Pandas

# Numpy

In [ ]:
import numpy as np

In [ ]:
#1d Array
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))

In [ ]:
print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)
print(arr1.itemsize) #bits per element
print(arr1.nbytes) #elements * bits = total_num

In [ ]:
arr2 = np.array([10,5,1,0],dtype=np.float64)
print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)
print(arr1.itemsize)
print(arr1.nbytes)
arr2=arr2.reshape((1,4)) # 1 row 4 column
print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)
arr2=arr2.reshape((4,1)) # 4 row 1 column
print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

In [ ]:
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)
print(arr3.shape)
print(arr3.ndim)
print(arr3.dtype)

### array creation using inbuild methods
- np.zero(shape,dtype)
- np.ones(shape,dtype)
- np.full(shape,value)
- np.eye(n)
- np.arrange(start,stop,step)

In [ ]:
zero_matrix = np.zeros((3,3),np.float32)
print(zero_matrix)
ones_matrix = np.ones((3,3))
print(ones_matrix)
filled_matrix = np.full((3,3),7.0)
print(filled_matrix)
indentity_matrix = np.eye(3)
print(indentity_matrix)
basic_matrix = np.arange(10,100,10).reshape(3,3)
print(basic_matrix)

### np.linspace(start, stop, num)
- inclusive start and stop
- provides linearly distant points
- used mainly in graph plotting, activation function

In [ ]:
linearly_spaced_matrix1 = np.linspace(1,3,5)
print(linearly_spaced_matrix1)
linearly_spaced_matrix2 = np.linspace(1,1.001,5)
print(linearly_spaced_matrix2)
linearly_spaced_matrix3 = np.linspace(0,10,5)
print(linearly_spaced_matrix3)
linearly_spaced_matrix4 = np.linspace(11,99,5)
print(linearly_spaced_matrix4)

In [ ]:
# ops
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(np.sqrt(a))

In [ ]:
print(a)
print(a.T)          #Transpose
print(a.min())      #min val
print(a.max())
print(a.argmax())   #max val index like its a 1d array
print(a.ravel())    #flatten the arr
print(np.where(a<3)) # 1 and 2 at indexes (0,0) and (0,1)

In [ ]:
a[a>2]

## Random num generator

- requires creating a generator using:
- rng = np.random.default_rng(seed = seed)


In [ ]:
rng1 = np.random.default_rng() #seedless always different random number
rng2 = np.random.default_rng(seed = 11) #with seed same random number

In [ ]:
print(rng1.random((2,2)))
print(rng2.random((2,2)))

- rng.random((size)) -> gives a uniform distribution [0,1)  

In [ ]:
print(rng1.random())                # float in [0.0, 1.0)
print(rng1.random(5))               # 1D array of 5 random floats
print(rng1.random((2, 3)))          # 2x3 array of random floats

- rng.integers(low,high,size) 

In [ ]:
print(rng1.integers(0, 10))         # int in [0, 10)
print(rng1.integers(0, 10, size=5)) # array of 5 ints


- normal distributed array: rng.standard_normal((size))

In [ ]:
normal_dist = rng1.standard_normal((3,3))
normal_dist

- choice and Permutation

In [ ]:
sample_arr = rng1.choice([x for x in range(1,10)], (2,2))
sample_arr

In [ ]:
shuffle_arr = rng1.permutation(np.arange(1,6,1))
shuffle_arr

## Axis in matrix/ np arrays
- axis 0 -> column wise
- axis 1 -> row wise

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.sum())
print(arr.sum(axis=0)) # vertical sum top to down
print(arr.sum(axis=1)) # horizontal sum left to right

### additionals

In [ ]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Mean:")
print(mean)

print("std_dev:")
print(std_dev)

print("Normalized array:")
print(normalized_array)

In [ ]:
# Create a NumPy array of shape (3, 3) filled with random integers
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)

In [ ]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

In [ ]:
# Create two NumPy arrays of shape (2, 3) and (3, 2)
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform matrix multiplication
result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

In [ ]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Flatten the array
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

In [ ]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

In [ ]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
#distance(i, j) = √[(xᵢ - xⱼ)² + (yᵢ - yⱼ)²]
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)
print(distances.dtype)

distance(i, j) = √[(xᵢ - xⱼ)² + (yᵢ - yⱼ)²]

This produces a 3x3 matrix like:

[[d(0,0) d(0,1) d(0,2)]
 [d(1,0) d(1,1) d(1,2)]
 [d(2,0) d(2,1) d(2,2)]]

🔍 Breaking down the distance line:
(data['x'][:, np.newaxis] - data['x'])**2


Let’s take it piece by piece.

data['x']:

This is just:

[1 3 5]

data['x'][:, np.newaxis]:

Adds a new axis to make it a column vector:

[[1]
 [3]
 [5]]


So now you can broadcast this against the row vector [1 3 5] to get all pairwise x-differences.

(data['x'][:, np.newaxis] - data['x']):

This gives you the matrix of xᵢ - xⱼ:

[[ 0 -2 -4]
 [ 2  0 -2]
 [ 4  2  0]]


Now square it:

[[ 0  4 16]
 [ 4  0  4]
 [16  4  0]]


Do the same for data['y'], you’ll get:

[[ 0  4 16]
 [ 4  0  4]
 [16  4  0]]

Add the squared differences:
(x_diff_squared) + (y_diff_squared)

[[ 0  8 32]
 [ 8  0  8]
 [32  8  0]]

Take the square root:
np.sqrt(...)

[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]

In [ ]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

# Pandas

In [ ]:
import pandas as pd

In [ ]:
data = np.random.randint(1,10,size=(5,))
print("data: ",data)
series = pd.Series(data)
print("series: \n",series)
type(series)

In [ ]:
data2 = {'a':1,'b':4,'c':3}
data2 = pd.Series(data2)
print(data2)
data3 = pd.Series([1,2,3,4,5], index=['a','b','c','d','f'])
print(data3)

## Dataframe

In [ ]:
data4 = {
    'Name':['Vanitas','Alice','Oz'],
    'Age':[21,17,15],
    'City':['Paris','Abbys','Abbys']
}
print(type(data4)) 
df = pd.DataFrame(data4)
print(df) #basic view
print('data_type: ',type(df))
df #formated view

In [ ]:
url = "https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv"
df = pd.read_csv(url)
df.head()

In [ ]:
df.tail()

In [ ]:
df.loc[0]

In [ ]:
df.iloc[0] #not 0th index but 0th position, will return same even if
           #we used a DF with non integer indexes

In [ ]:
df.columns

In [ ]:
df['Index']

In [ ]:
df[' "Weight(Pounds)"']

In [ ]:
df.at[2,' "Weight(Pounds)"']

In [ ]:
df.iat[1,1]

### data manipulation in df

In [ ]:
# df['Mew']==[x for x in range(10000, 2010000,10000)]

In [ ]:
df['Salary']=[x for x in np.random.randint(10000,20000,size=(200,))]

In [ ]:
df.head()

In [ ]:
df.drop('Salary', axis=1, inplace=True) # axis 1 as thats the way it traverse
#in terms of index like:

# -axis 1->
# 1 1 1  |
# 2 2 2  axis 0
# 3 3 3  |
#        V
# but in pandas axis 1 drop means traverse indexs in axis 1 
# i.e, column named Salary and drop said column


In [ ]:
df

In [ ]:
df.rank().head()

In [ ]:
df.head()

In [ ]:
print(df.loc[:3]," \n",df.iloc[-3:])

In [ ]:
df.iat[2,2]

In [ ]:
df.describe()

In [ ]:
df.info()

In [ ]:
df.rename(columns={' Height(Inches)"':'Height(Inches)'},inplace=True)
df.rename(columns={' "Weight(Pounds)"':'Weight(Pounds)'},inplace=True)
df.head()

In [ ]:
df.dtypes

In [ ]:
groupped = df.groupby('Height(Inches)')['Salary'].mean()
groupped 

### DM

In [ ]:
df.head()

In [ ]:
# Handling missing value
df.isnull()

In [ ]:
df.isnull().any()

In [ ]:
df.isnull().sum()

In [ ]:
# filling missing values with mean of the column
df['Salary_fill_NA']=df['Salary'].fillna(df['Salary'].mean())

In [ ]:
df

In [ ]:
#rename!
df = df.rename(columns={
    ' Height(Inches)"': 'Heights',
    ' "Weight(Pounds)"': 'Weight'
})
df.head()

In [ ]:
df.columns = df.columns.str.strip().str.replace('"', '')

print(df.columns)


In [ ]:
df.head()

In [ ]:
#changing data type
df['MewMew']=df['Salary'].astype(float)
df.head()

In [ ]:
df['MewMew']=df['MewMew'].astype('double')
df.head()

In [ ]:
df['Salary_Increased']=(df['Salary']*1.1).astype('double')
df['Salary_Increament']=(df['Salary']*0.1).astype('double')
df.head()

In [ ]:
df['MewMew']=df['MewMew'].apply(lambda x:x/20) #yes here we can put a custom function 
df.head()

In [ ]:
#data aggregating and grouping
df['even_or_odd']=df['Index']%2
df['even_or_odd'] = df['even_or_odd'].map({0: 'Even', 1: 'Odd'})
df2=df.groupby('even_or_odd').mean()
# df.head()
df2

In [ ]:
df3=df.groupby('even_or_odd').agg(['mean','sum','count'])
df3.head()

In [ ]:
# Merging dataframes
df4 = pd.DataFrame({'Key':['A','B','C'], 'Values':[1,2,3]})
df5 = pd.DataFrame({'Key':['A','B','D'], 'Values':[4,5,6]})


In [ ]:
df4

In [ ]:
df5

In [ ]:
# merging em on 'Key' columns
pd.merge(df4,df5,on='Key',how='inner')

In [ ]:
pd.merge(df4,df5,on='Key',how='outer')

In [ ]:
pd.merge(df4,df5,on='Key',how='left')

In [ ]:
dfNAN=pd.merge(df4,df5,on='Key',how='right')
dfNAN

In [ ]:
dfNAN.isna().sum()

In [ ]:
from io import StringIO
employee_data = '{"employee_name": ["Vanitas", "Aqua", "Terra"], "email": ["vanitas@example.com", "aqua@example.com", "terra@example.com"], "department": ["R&D", "HR", "Finance"], "salary": [75000, 68000, 72000]}'

In [ ]:
employee_data

In [ ]:
df6=pd.DataFrame(StringIO(employee_data))
df6

In [ ]:
df7=pd.read_json(StringIO(employee_data))
df7

In [ ]:
df7.to_json() #based on index   

In [ ]:
df7.to_json(orient='index') #based on index again this is default   

In [ ]:
df7.to_json(orient='records') #based on record   

In [ ]:
df7.head()

In [ ]:
df8=pd.read_csv("https://gist.githubusercontent.com/tijptjik/9408623/raw/wine.csv",header=None)
df8

In [ ]:
df8.describe()

In [ ]:
df8.to_csv("wine_no_header.csv")

In [ ]:
df9=pd.read_csv("https://gist.githubusercontent.com/tijptjik/9408623/raw/wine.csv")
df9

In [ ]:
df9.head()

In [ ]:
df9.describe()

In [ ]:
df9.to_csv("wine_data.csv")

In [ ]:
%pip install lxml
%pip install beautifulsoup4

In [ ]:
# reading from html table
url1 = "https://www.fdic.gov/bank-failures/failed-bank-list"
df10=pd.read_html(url1)
df10

In [ ]:
df10[0]

In [ ]:
%pip install requests

In [ ]:
import requests

In [ ]:
url2='https://en.wikipedia.org/wiki/Mobile_country_code'
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

# Fetch page content with requests
response = requests.get(url2, headers=headers)
html_content = response.text
df11 = pd.read_html(html_content)
df11

In [ ]:
df12 = pd.read_html(html_content,match='Country')
df12

In [ ]:
df11[0]

In [ ]:
df11[1]

In [ ]:
df11[2]

In [ ]:
df12[0]

In [ ]:
df12[0].isnull()

In [ ]:
df12[0].isnull().any()

In [ ]:
df12[0].isnull().sum()

In [ ]:
# pd.read_excel('path/file.xlsx') this is how u read an xl file

A pickle file is a way to save Python objects (like lists, dictionaries, DataFrames, models, etc.) to a file so you can load them later without recomputing or recreating them.

- It uses Python's built-in pickle module.

- It serializes (converts) objects into a byte stream and saves it.

- Later, you can deserialize (load) the object back into Python exactly as it was.

Example use: saving a trained machine learning model or a processed DataFrame for quick reuse.

In [ ]:
df12[0].to_pickle('pickleFile')

In [ ]:
pd.read_pickle('pickleFile')

# Matplotlib

**Matplotlib** is a popular Python library used for creating **static, animated, and interactive visualizations** such as:

- Line plots
- Bar charts
- Histograms
- Scatter plots

It is highly customizable and works well with libraries like NumPy and Pandas. The most common interface is `pyplot`, which offers MATLAB-like plotting functions.

---

### Line Plot

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x = [1, 2, 3, 4, 5]
y = [2, 3, 5, 7, 11]
plt.plot(x, y)
plt.title('Simple Line Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.show()

In [ ]:
import numpy as np
arr1 = np.array([x for x in range(1,11,1)])
arr2 = np.array([x**2 for x in arr1])
plt.plot(arr1,arr2)
plt.xlabel('Value')
plt.ylabel('Value Squared')
plt.title('MewMew')
plt.show()

In [ ]:
arr1 = np.linspace(0,3,17)
arr2 = np.array([x**2 for x in arr1])
plt.plot(arr1,arr2,color='red',linestyle='-.',marker='o',linewidth=1,markersize=3)
plt.xlabel('Value')
plt.ylabel('Value Squared')
plt.title('MewMew')
plt.show()

In [ ]:
#Multiple plots
x = np.linspace(-100,100,105)
y = np.sin(x)
z = np.cos(x)
e = np.exp(x)

# we use sub plot for multiple plotting:
plt.figure(figsize=(15,15))

plt.subplot(2,2,1)
plt.plot(x,y,color='red')
plt.title('x+sin')


plt.subplot(2,2,2)
plt.plot(x,z,color='blue')
plt.title('x+cos')

plt.subplot(2,2,3)
plt.plot(x,e,color='green')
plt.title('x+exp')

plt.subplot(2,2,4)
plt.plot(y,z,color='magenta')
plt.title('sin+cos')

print(f'x: {x}')
print(f'y: {y}')
print(f'z: {z}')
print(f'e: {e}')

In [ ]:
base = np.linspace(0,100,20000)
x = np.sin(base)
y = np.cos(base)

plt.figure(figsize=(15,15))

plt.subplot(3,1,1)
plt.plot(base,x,color='red')
plt.title('sine')

plt.subplot(3,1,2)
plt.plot(base,y,color='blue')
plt.title('cosine')


plt.subplot(3,1,3)
plt.plot(x,y,color='purple')
plt.title('Amalgamation')

# plt.show()

In [ ]:
# b=np.linspace(0,200,10)
# base = np.linspace(0,100,20000)
base = np.linspace(-100,100,105)
x=np.sin(base)
y=np.cos(base)
plt.figure(figsize=(15,15))
# plt.plot(base,x,color='red',linestyle='-.')
# plt.plot(base,y,color='blue',linestyle='--')
plt.plot(x,y,color='hotpink')
base2 = np.linspace(-200,200,105)
x=np.sin(base2)
y=np.cos(base2)
plt.plot(x,y,color='pink')
base2 = np.linspace(-500,500,205)
x=np.sin(base2)
y=np.cos(base2)
plt.plot(x,y,color='violet')

### BarPlot

In [ ]:
catagories=['a','b','c','d','e']
values = np.random.randint(5,100,5)
fig = plt.figure()
ax = fig.add_axes([0.2,0.2,0.8,0.8]) #.add_axes([left, bottom, width, height])
# left = 0: start at the very left of the figure.
# bottom = 0: start at the very bottom.
# width = 1: use 100% of the width.
# height = 1: use 100% of the height.
plt.bar(catagories,values,color='aqua')
plt.xlabel('catagories')
plt.ylabel('values')
plt.show()

### Histogram
- used for distribution of dataset

In [ ]:
import pandas as pd

In [ ]:
data = np.random.randint(1,6,20)
print(data)
# print(map(set(data),data+1))


counts = pd.Series(data).value_counts().sort_index()
print(counts)
plt.hist(data,bins=[1,2,3,4,5,6],color='blue',edgecolor='white')
plt.ylabel('count')
plt.xlabel('values')
# plt.table(data)


In [ ]:
data = np.random.randint(1,6,10)
print(data)
# print(map(set(data),data+1))


counts = pd.Series(data).value_counts().sort_index()
print(counts)
plt.hist(data,bins=[1,2,3,4,5],color='blue',edgecolor='white')
plt.ylabel('count')
plt.xlabel('values')

# Convert counts to table data
table_data = [[val] for val in counts.values]
row_labels = [str(i) for i in counts.index]
col_labels = ['Count']

# Add table below the histogram
table = plt.table(
    cellText=table_data,
    rowLabels=row_labels,
    colLabels=col_labels,
    cellLoc='center',
    loc='bottom'
)

table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1, 1.2)

plt.tight_layout()
plt.show()

In [ ]:
data = np.random.randint(1, 6, 20)
counts = pd.Series(data).value_counts().sort_index()

# Prepare table data
table_data = [[val] for val in counts.values]
# counts is a Pandas Series that holds the frequency of each value (1–5) in your dataset.
# counts.values gives you just the frequencies, e.g., [3, 4, 5, 6, 2] (these are example frequencies).
# We wrap each value in a list: [[3], [4], [5], [6], [2]]
# Why? Because plt.table() expects cellText to be a 2D list, where each sublist represents a row in the table.
row_labels = [str(i) for i in counts.index]
# counts.index are the unique values from the original data, e.g., [1, 2, 3, 4, 5]
# str(i) converts the index (which are integers) to strings, as required for table labels.
# So row_labels becomes: ['1', '2', '3', '4', '5']
col_labels = ['Count']

# Create two subplots: one for histogram, one for table
fig, (ax1, ax2) = plt.subplots(
    2, 1,
    figsize=(6, 6),
    gridspec_kw={'height_ratios': [4, 1]}
)

# --- Plot histogram ---
ax1.hist(data, bins=4, color='blue', edgecolor='white')
ax1.set_ylabel('Count')
ax1.set_xlabel('Values')
ax1.set_title('Histogram with Value Count Table')

# --- Plot table ---
ax2.axis('off')  # Hide the actual subplot axes
table = ax2.table(
    cellText=table_data,
    rowLabels=row_labels,
    colLabels=col_labels,
    loc='center',
    cellLoc='center'
)
table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1, 1.2)  # Adjust size of table cells

# Tidy layout
plt.tight_layout()
plt.show()

### ScatterPlot

In [ ]:
x = np.random.randint(0,100,1000)
y = np.random.randint(0,100,1000)

plt.scatter(x, y, color='blue', marker='.', s=8,alpha=0.5)  # Use s=2 for marker size
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.title('Random Scatter Plot')
plt.grid(True)
plt.show()

### Pie Chart

In [ ]:
# Data
labels = ['Watermelon', 'Orange', 'Cherries', 'Mango']
sizes = [25, 30, 20, 25]  # Percentages or raw values
colors = ['red', 'orange', 'lightcoral', 'yellow']
explode = [0.2,0,0,0]

# Plot
# plt.pie(sizes, labels=labels,explode=explode, colors=colors, shadow=True)
plt.pie(sizes, labels=labels,explode=explode, colors=colors, autopct='%1.1f%%', shadow=True)
plt.title('Fruit Distribution')
plt.axis('equal')  # Makes the pie chart a circle

plt.show()

In [ ]:
# Data
labels = ['Watermelon', 'Orange', 'Cherries', 'Mango']
sizes = [25, 30, 20, 25]
colors = ['red', 'orange', 'lightcoral', 'yellow']

# Dynamically explode only the max value
max_index = sizes.index(max(sizes))
explode = [0.1 if i == max_index else 0 for i in range(len(sizes))]

# Plot
plt.pie(
    sizes,
    labels=labels,
    explode=explode,
    colors=colors,
    autopct='%1.1f%%',
    shadow=True,
    startangle=90
)
plt.title('Fruit Distribution')
plt.axis('equal')

plt.show()

In [ ]:

labels = ['Watermelon', 'Orange', 'Cherries', 'Mango']
sizes = [23, 30, 20, 27]
colors = ['red', 'orange', 'lightcoral', 'yellow']

# Explode slices where size >= 25
explode = [0.1 if size > 25 else 0 for size in sizes]

plt.pie(
    sizes,
    labels=labels,
    explode=explode,
    colors=colors,
    autopct='%1.1f%%',
    shadow=True,
    startangle=90
)
plt.title('Fruit Distribution')
plt.axis('equal')
plt.show()

### additional dataset operations

In [ ]:
import seaborn as sns

# Load the 'tips' dataset
df = sns.load_dataset('tips')
df.head()

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.isnull().sum()

In [ ]:
df.groupby('time')['tip'].sum()

In [ ]:
df2 = sns.load_dataset('flights')
df2.info()

In [ ]:
catagorized = df2.groupby('month')['passengers'].sum()
catagorized

In [ ]:
catagorized.plot(kind='bar',color='teal')
plt.xlabel('Month')
plt.ylabel('Total Passengers')
plt.title('Total Passengers per Month')
plt.show()

In [ ]:
df2.info

In [ ]:
#trend year-wise:
trend = df2.groupby('year')['passengers'].sum().reset_index()
trend

In [ ]:
plt.plot(trend['year'],trend['passengers'],marker='o',linestyle='-.')

# Seaborn

In [ ]:
import seaborn as sns

In [ ]:
inbuild_datasets1 = sns.load_dataset('diamonds')
inbuild_datasets1.head()

In [ ]:
inbuild_datasets2 = sns.load_dataset('brain_networks')
inbuild_datasets2.head()

In [ ]:
tips = sns.load_dataset('tips')
tips.head()

In [ ]:
#creating a scatter plot
import matplotlib.pyplot as plt

sns.scatterplot(x='total_bill',y='tip',data=tips)
plt.title("MewMew")
plt.grid(True)

In [ ]:
#line plot
sns.lineplot(x='size',y='total_bill',data=tips)
plt.title("MEWMEMWEMWMEEMWMWMEWMEMW")

In [ ]:
#catagorical graph
sns.barplot(x='day',y='total_bill',data=tips)

In [ ]:
#box plot
sns.boxplot(x='day',y='total_bill',data=tips)
#outliers and percentile stuff

In [ ]:
sns.violinplot(x='day',y='total_bill',data=tips)
#distributions and such

In [ ]:
sns.histplot(tips['total_bill'],bins=10)

In [ ]:
sns.histplot(tips['total_bill'],bins=10,kde=True)

In [ ]:
#KDE
sns.kdeplot(tips['total_bill'],fill=True)

In [ ]:
#PairPlot
sns.pairplot(tips)
#RELATIONSSS between each and every other feature

In [ ]:
corr=tips[['total_bill','tip','size']].corr()
corr #correlation

In [ ]:
sns.heatmap(corr,annot=True,cmap='coolwarm')